### ISSUE TITLE
Equations displayed on markdown are transparent. 

### ISSUE THREAD

**Issue by neldivad** [sidharrth2002/text-scoring#1]
Typing out equations in markdown is hard so I get that you're using images as a solution. But the images you use are transparent svg, so people can't actually see them in the markdown.

**Comment by sidharrth2002** [comment]
Hi @neldivad , I realised this problem, the equations were only visible in light mode. Will find a solution to this 😅

**Comment by sidharrth2002** [comment]
https://github.blog/2022-05-19-math-support-in-markdown/
